version: "3.9"

services:
  web:
    build: ..
    command: bash -c "uvicorn internal.run:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ../.env

  db:
    image: postgres:15

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=cats_db

    ports:
      - "5432:5432"